% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
  xelatex,ja=standard, b5paper]{bxjsbook}
\title{タイトル}
\author{著者名}
\date{}

\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={タイトル},
  pdfauthor={著者名},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\makeatletter
\def\emptypage@emptypage{%
    \hbox{}%
    \thispagestyle{headings}%
    \newpage%    
}%
\def\cleardoublepage{%
        \clearpage%
        \if@twoside%
            \ifodd\c@page%
                % do nothing
            \else%
                \emptypage@emptypage%
            \fi%
        \fi%
    }%
\makeatother
\usepackage{fancyhdr}
\fancypagestyle{plain}{\pagestyle{fancy}}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
\hypertarget{hajimeni}{%
\chapter*{はじめに}\label{hajimeni}}
\addcontentsline{toc}{chapter}{はじめに}

本書『\textbf{Rで読むExcelファイル}』を書こうと思ったのは「RとRStudioを使いたい！と思う人がもっと増えればいいのに」という願いからです。使う人が多くなれば、新しい知識に出会いやすくなりますし、仕事でも使う機会が増える可能性があります。

使う人を増やすためにはよい入門書やwebサイトが必要ですが、それは巷にあふれていて無料でアクセスできるものも多いです。

例えば

\begin{itemize}
\tightlist
\item
  \href{https://r4ds.had.co.nz/}{R for Data Science}（英語） \footnote{\url{https://r4ds.had.co.nz/}}\strut \\
\item
  \href{https://kazutan.github.io/JSSP2018_spring/index.html}{日本社会心理学会　第5回春の方法論セミナー　RとRstudio入門} \footnote{\url{https://kazutan.github.io/JSSP2018_spring/index.html}}
\end{itemize}

そこで本書では目的を絞って、R（実際はすべてRStudioから使います）を使いたいと思わせる部分を解説することを目指します。Rでどんな便利なことができるか、入門書などでもあまり深く解説されてない部分にフォーカスして紹介します。

\hypertarget{ux672cux66f8ux306eux7279ux5fb4}{%
\section*{本書の特徴}\label{ux672cux66f8ux306eux7279ux5fb4}}
\addcontentsline{toc}{section}{本書の特徴}

便利なことといってもいろいろあるので、その中でも、つまづくと嫌になってしまうことの多そうな、\textbf{「手元のExcelファイルを読み込む」}所に着目しました。このトピックだけをRのいわゆるモダンな方法を使って重点的に解説した資料は、筆者の知る範囲では見つけられてないので、本書の最も際立った特徴といえます。また、関連するファイル形式として、csvファイルの読み書きも少しだけ触れています。こちらはつまづくことの多いであろう文字コードについても解説しました。

解析したいデータが、綺麗な一つにまとまったデータばかりとは限りません。たとえば、会社の部署ごとに分かれたデータなど、解析に持っていくまでに大量のファイルを読みこまなければいけない場合もあります。その読み込みの際にいかに楽をできるかという点を意識しています。データさえスムーズに読み込めれば、後はすぐれた解説がネット上でもたくさんあり、やりたいことが可能になる環境が整うからです。

Excelファイルをただ読みこむといってもいろんなバリエーションが考えられます。その単なる読みこみプロセスを通じて、Rを使う上で便利な関数や手続きを学ぶこともできるでしょう。\textbf{戦いの中で自然に強くなった的な効果}も見込めるかもしれません。

本書の内容は、githubレポジトリの \url{https://github.com/izunyan/excel_r} ですべて公開しています。コードやサンプルデータはこちらのレポジトリをダウンロードしてお試しください。pdf版が読みたい方は、以下のページで無料で入手可能です。自力でできる方は、\texttt{Build\ Book}でも作成できます。

\begin{itemize}
\tightlist
\item
  \href{https://techbookfest.org/product/4794168259903488?productVariantID=5913872206659584}{技術書典マーケットの販売ページ}

  \begin{itemize}
  \tightlist
  \item
    \url{https://techbookfest.org/product/4794168259903488?productVariantID=5913872206659584}
  \end{itemize}
\end{itemize}

\hypertarget{ux60f3ux5b9aux8aadux8005}{%
\subsection*{想定読者}\label{ux60f3ux5b9aux8aadux8005}}
\addcontentsline{toc}{subsection}{想定読者}

色々なExcelファイルを読み込んで分析する機会があるのであれば、全くRのことを知らない方から、少しRの経験があるけど複数のファイルを一度に読みこんだことはないというレベルの方ぐらいまでが対象となるでしょう。

本書の到達目標は、RでのExcelファイルの読み書きレベルをある程度高める、という所に定めました。その先は是非好きなように可視化なり解析なり進めていただければと思います。とはいえ、そこでお好きなように！と言われても路頭に迷う方もいるかもしれないので、データの内容把握に関して、要約値や欠損値の一覧、簡単な可視化、相関の一覧についても少しだけ解説しました。その一助として、特別付録として本書と並行してまとめた、可視化のための\href{https://izunyan.github.io/practice_ggplot2/}{ggplot2の辞書}（\protect\hyperlink{huroku}{特別付録について}参照）もあります。

なお、データをきれいにする過程（例：前処理、データクリーニング、データクレンジング、データラングリングなど）については多くの説明を要するため、本書の範囲を超えます。これはまた別機会にまとめられたらなと思っています。

\hypertarget{structure}{%
\subsection*{本書の構成}\label{structure}}
\addcontentsline{toc}{subsection}{本書の構成}

まず\ref{project}章では、RStudioでファイルを読み書きする際に、最低限知っておいた方がよい知識について解説しておきます。とっつきにくいかもしれませんが、知っておいてよかったと後になって実感する類のものなので、使って慣れていきましょう。

\ref{readexcel}章は本書のメインであるExcelファイルの読み込みについて解説します。一つのファイルの読み込みから、複数シート、複数ファイルの読み込みまで、様々なシーンに対応しました。また、読みこんだファイルを一つのデータフレーム\footnote{変数（列）とオブザベーション（行）が碁盤の目のようになった集まりの形のデータ。Excelであれば通常1行目に列名が入り、2行目以降が個別のデータを表す。データ解析において便利で分かりやすいため、本書ではデータフレームの形で説明していく}にまとめる方法についても触れています。

\ref{writeexcel}章はExcelファイルの保存についてです。ここでも、一つのファイルの保存から、複数ファイルの保存まで解説します。ここまでの内容が理解できれば、大量ファイルの読み書きにまつわる単純な繰り返し作業とはさよならできるでしょう。

\ref{readsavecsv}章は関連知識としてcsvファイルの読み込みと保存について解説します。windowsユーザーは文字コードの違いによる文字化けというつらみと対峙することになり、初学者はここで脱落していくことが多いのではないかと思います。そのために、サバイバルスキルとして知っておくことが有用だと思い書いておきました。自分が相当苦しんだので\ldots{}

\ref{dataanal}章は、読み込んだファイルの特徴をざっと把握する方法について解説しました。ここまでやれば、（きれいなデータであれば！）きっとデータ解析に入っていくことができるでしょう。

\hypertarget{ux57f7ux7b46ux74b0ux5883}{%
\subsection*{執筆環境}\label{ux57f7ux7b46ux74b0ux5883}}
\addcontentsline{toc}{subsection}{執筆環境}

\begin{itemize}
\item
  本書は\href{https://bookdown.org/}{bookdown}にて執筆しました \footnote{\url{https://bookdown.org/}}
\item
  RおよびRStudio、パッケージのバージョン

  \begin{itemize}
  \tightlist
  \item
    R version 3.6.1
  \item
    RStudio version 1.3.1073
  \item
    readxl version 1.3.1
  \item
    tidyverse version 1.3.0
  \end{itemize}
\end{itemize}

\hypertarget{ux6ce8ux610fux4e8bux9805ux306aux3069}{%
\section*{注意事項など}\label{ux6ce8ux610fux4e8bux9805ux306aux3069}}
\addcontentsline{toc}{section}{注意事項など}

\begin{itemize}
\item
  本書の内容はすべてwindows環境を想定しています。
\item
  この本に書いてある内容は、筆者が学習したことをまとめているものにすぎないため、正常な動作の保証はできません。使用する際は、自己責任でお願いします。
\end{itemize}

\hypertarget{huroku}{%
\section*{特別付録について}\label{huroku}}
\addcontentsline{toc}{section}{特別付録について}

本書の執筆に先駆けて、順序が違う気がしますがまず付録の作成からはじめました。特別付録は以下でアクセス可能なオンライン付録となります。

\begin{itemize}
\tightlist
\item
  \href{https://izunyan.github.io/practice_ggplot2/}{ggplot2の辞書}

  \begin{itemize}
  \tightlist
  \item
    \url{https://izunyan.github.io/practice_ggplot2/}
  \end{itemize}
\end{itemize}

Twitterで応援してもらったら項目が増えていく仕様にしているので、もっと読みたい方は\href{https://twitter.com/matsuchiy/status/1277621662708453377}{こちらのツイート}に何らかのレスポンスください！

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{project}{%
\chapter{前提：プロジェクトの設定}\label{project}}

Rの基本的な使い方は他の情報源にゆだねていますが、ここだけは避けて通れないので解説しておきます。

\hypertarget{ux3069ux306eux30d5ux30a9ux30ebux30c0ux306eux30d5ux30a1ux30a4ux30ebux304bux306eux6307ux5b9a}{%
\section{どのフォルダのファイルかの指定}\label{ux3069ux306eux30d5ux30a9ux30ebux30c0ux306eux30d5ux30a1ux30a4ux30ebux304bux306eux6307ux5b9a}}

Excelファイルに限らず、ファイルをRに読み込む際は、どのフォルダから読むのか、位置を正確に指定する必要があります。

そこで重要となる概念が、「作業フォルダ」というものです。

コンソールに\texttt{getwd()}と打って出てくるフォルダが現在の作業フォルダになります。

\hypertarget{projecttoha}{%
\section{プロジェクトとは}\label{projecttoha}}

RStudioの「プロジェクト」とは、作業フォルダにまつわる面倒な設定を意識しないですむ非常に便利な機能です。RStudioを開いて右上のところに設定アイコンがあります（Figure\ref{fig:projectfig}）。

ざっくり説明すると、データを加工して解析する際に、1つのフォルダ（サブフォルダも含む）の中に関連するデータやコード、出力をまとめておき、そのフォルダをプロジェクトとして設定するのです。これにより、ファイルの読み書きの際の場所指定をいちいち意識しないで作業できるようになります。

したがって、本書に出てくる内容をご自身のPC上で再現するには、Githubレポジトリhttps://github.com/izunyan/excel\_r をダウンロードして、その中にある\texttt{excel\_r.Rproj}ファイルを実行すればお手軽です。

詳しくは、先述のR for Data Scienceでの\href{https://r4ds.had.co.nz/workflow-projects.html}{解説}が参考になります。\footnote{\url{https://r4ds.had.co.nz/workflow-projects.html}}

\hypertarget{readexcel}{%
\chapter{Excelファイルの読み込み}\label{readexcel}}

\hypertarget{readoneexcel}{%
\section{一つのExcelファイルを読み込む}\label{readoneexcel}}

\hypertarget{junbiyomikomi}{%
\subsection{ファイルの準備と読み込み}\label{junbiyomikomi}}

ExcelファイルをRに読み込むには、\texttt{readxl}パッケージが便利です。\footnote{以下、まだインストールしていないパッケージがあれば、\texttt{install.packages("")}の\texttt{""}中にパッケージ名を入れて実行するか、RStudioの\texttt{Packages}タブの\texttt{Install}からインストールしてください}セクション\ref{projecttoha}で述べた通り、ここからは、githubレポジトリのhttps://github.com/izunyan/excel\_r をダウンロードしてプロジェクトを開いて進めてみてください。dataフォルダ（\texttt{data/}で表現）に入っている「ペンギン.xlsx」\footnote{Horst AM, Hill AP, Gorman KB (2020). palmerpenguins: Palmer Archipelago
  (Antarctica) penguin data. R package version 0.1.0.
  \url{https://allisonhorst.github.io/palmerpenguins/}}を読み込んでみましょう。

読み込みには\texttt{read\_xlsx()}関数を使います。したがって、以下すべてExcelファイル形式は\texttt{.xlsx}を想定します。\texttt{read\_xls()}や\texttt{read\_excel()}という関数もあるので、ファイル形式によって使い分けられます。ファイル形式が混ざっている時は\texttt{read\_excel()}が有用かもしれません。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(readxl)}

\NormalTok{df }\OtherTok{\textless{}{-}} 
 \FunctionTok{read\_xlsx}\NormalTok{(}\StringTok{"data/ペンギン.xlsx"}\NormalTok{) }\CommentTok{\# Excelファイルの読み込み}

\NormalTok{df }\CommentTok{\# データの表示 }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 344 x 9
##   species 種類     island    bill_length_mm bill_depth_mm
##   <chr>   <chr>    <chr>              <dbl>         <dbl>
## 1 Adelie  アデリー Torgersen           39.1          18.7
## 2 Adelie  アデリー Torgersen           39.5          17.4
## 3 Adelie  アデリー Torgersen           40.3          18  
## # ... with 341 more rows, and 4 more variables:
## #   flipper_length_mm <dbl>, body_mass_g <dbl>, sex <chr>,
## #   year <dbl>
\end{verbatim}

上記コードを実行すると、RStudioの右上（デフォルトの配置であれば）のEnvironmentタブに、

\begin{verbatim}
df  344 obs. of 9 variables
\end{verbatim}

という表示が出ると思います。つまり、344行のデータと9列の変数が入っているデータを、\texttt{df}という名前のもの（オブジェクト）としてRに読みこんだ、ということを示しています。\texttt{df\ \textless{}-}の部分がその作業に該当します。\texttt{\textless{}-}の右側の内容を左側のオブジェクトに格納するという意味です。ここで読み込まれた形がデータフレーム（\protect\hyperlink{structure}{はじめに\textgreater 本書の構成}の注参照）です。

オブジェクト名である\texttt{df}と打つことで、デフォルトでは最初の10行分のデータが表示されます。ここでは紙面の都合で設定を変えているので3行だけにしています。表示された最初の行にも、\texttt{A\ tibble:\ 344\ x\ 9}と、行数x列数の情報が出ています。表示しきれなかった行は、\texttt{with\ 341\ more\ rows}と省略され、表示しきれなかった列は、\texttt{flipper\_length\_mm\ \textless{}dbl\textgreater{},\ body\_mass\_g\ \textless{}dbl\textgreater{},\ sex\ \textless{}chr\textgreater{},\ year\ \textless{}dbl\textgreater{}}と、\texttt{名前\textless{}データの型名\textgreater{}}が表示されます。なお、読みこんだファイルの保存については\ref{writeoneexcel}章で解説します。

\hypertarget{hokan}{%
\subsubsection{最高な機能だよ！パスの自動補完}\label{hokan}}

\texttt{read\_xlsx("")}と打った後に、\texttt{"\ "}の中にカーソルを置いて、tabキーを押すと、プロジェクトの中身が一覧で表示されるので、選んでいくだけで目的のファイルがキーボードを打つことなしに選べます！RStudioは\texttt{"\ "}と打てばどこでもこの補完が可能です。\footnote{ただし、R version 4.0で文字コード関連の挙動が変わったみたいで、R 4.0.2ではエラーになりました\ldots（未解決）}

上の階層のフォルダに行きたいときは、\texttt{"\ "}の中に\texttt{../}と打てば可能です。その後にtabキーを押せば上の階層のフォルダが選べます。

\hypertarget{ux5217ux540dux5909ux6570ux540dux304cux3072ux3069ux3044ux5834ux5408ux306eux8aadux307fux8fbcux307f}{%
\subsection{列名（変数名）がひどい場合の読み込み}\label{ux5217ux540dux5909ux6570ux540dux304cux3072ux3069ux3044ux5834ux5408ux306eux8aadux307fux8fbcux307f}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{read\_xlsx}\NormalTok{(}\StringTok{"data/ペンギン（ひどい列名）ver.xlsx"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 344 x 9
##   Sｐｅｃｉｅｓ `種　類` `※島の名前` `①クチバシ　長さ（ｍｍ）`
##   <chr>         <chr>    <chr>                           <dbl>
## 1 Adelie        アデリー Torgersen                        39.1
## 2 Adelie        アデリー Torgersen                        39.5
## 3 Adelie        アデリー Torgersen                        40.3
## # ... with 341 more rows, and 5 more variables:
## #   ②ｸﾁﾊﾞｼ＿大きさ（ｍｍ） <dbl>, 翼：長さ(mm) <dbl>,
## #   ■体重　単位はｇ <dbl>, <U+329B><U+329A> <chr>, ２００７～２００９ <dbl>
\end{verbatim}

読めることは読めますが、今後のデータ処理を進めるうえで不安が残ります。

\hypertarget{ux30b9ux30daux30fcux30b9ux3084ux8a18ux53f7ux306aux3069ux3092ux81eaux52d5ux7684ux306bux5909ux63dbux3057ux3066ux304fux308cux308bux95a2ux6570ux3067ux304dux308cux3044ux306b}{%
\subsubsection{スペースや記号などを自動的に変換してくれる関数できれいに}\label{ux30b9ux30daux30fcux30b9ux3084ux8a18ux53f7ux306aux3069ux3092ux81eaux52d5ux7684ux306bux5909ux63dbux3057ux3066ux304fux308cux308bux95a2ux6570ux3067ux304dux308cux3044ux306b}}

\texttt{janitor}パッケージの\texttt{clean\_names()}関数を使って、列名に入り込んでいるスペースや記号などを安全な記号に変換します。

なお、日本語の列名では、\texttt{clean\_names()}関数に\texttt{case\ =\ "old\_janitor"}をつけないと読みにくい結果になります。このように、関数の中に追加する情報のことを引数（ひきすう）と言います。引数によってさまざまな条件を変更することが可能になります。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
    \CommentTok{\# ↑は普通まず最初に読み込むパッケージですが、本書ではここで初めて使います}
\FunctionTok{library}\NormalTok{(janitor)}

\FunctionTok{read\_xlsx}\NormalTok{(}\StringTok{"data/ペンギン（ひどい列名）ver.xlsx"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{clean\_names}\NormalTok{(}\AttributeTok{case =} \StringTok{"old\_janitor"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 344 x 9
##   sｐｅｃｉｅｓ 種_類    x_島の名前 x_クチバシ_長さ_ｍｍ
##   <chr>         <chr>    <chr>                     <dbl>
## 1 Adelie        アデリー Torgersen                  39.1
## 2 Adelie        アデリー Torgersen                  39.5
## 3 Adelie        アデリー Torgersen                  40.3
## # ... with 341 more rows, and 5 more variables:
## #   x_ｸﾁﾊﾞｼ_大きさ_ｍｍ <dbl>, 翼_長さ_mm <dbl>,
## #   x_体重_単位はｇ <dbl>, x_u_329b_u_329a <chr>,
## #   ２００７_２００９ <dbl>
\end{verbatim}

さて、ここで使われている \texttt{\%\textgreater{}\%} は非常に大事なので解説しておきます。

\hypertarget{pipe}{%
\subsubsection{\%\textgreater\% とは？}\label{pipe}}

「パイプ」と読みます。処理を重ねてコードに書いていきたい際に重宝し、現代の\texttt{tidyverse}を使ったRのコードに欠かせないものです。たとえば、データフレームdfのspecies列を選択する、という処理の

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{select}\NormalTok{(df, species)}
\end{Highlighting}
\end{Shaded}

は

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(species)}
\end{Highlighting}
\end{Shaded}

と書けます。 \texttt{\%\textgreater{}\%}の左側にあるものを右側の最初の部分（第1引数）に渡すという働きです。パイプの利点は、いくつもつないで書いていけることです。たとえば、ペンギンの種類別にクチバシの長さの平均値を出したいときには次のようにできます。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(species) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(平均値 }\OtherTok{=} \FunctionTok{mean}\NormalTok{(bill\_length\_mm, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 3 x 2
##   species   平均値
##   <chr>      <dbl>
## 1 Adelie      38.8
## 2 Chinstrap   48.8
## 3 Gentoo      47.5
\end{verbatim}

以下では\texttt{\%\textgreater{}\%}を多用していきます。

なお、ショートカット\texttt{ctrl\ +\ shit\ +\ M}（Macだと\texttt{Cmd\ +\ Shift\ +\ M}）で出せます。

\hypertarget{ux5168ux89d2ux534aux89d2ux3092ux81eaux52d5ux3067}{%
\subsubsection{全角←→半角を自動で}\label{ux5168ux89d2ux534aux89d2ux3092ux81eaux52d5ux3067}}

\texttt{stringi}パッケージの\texttt{stri\_trans\_nfkc()}関数を使って、変数名で全角-半角のばらつきを統一させます。

ここでは、変数名をリネームするのに\texttt{dplyr\ 1.0.0}で登場した\texttt{rename\_with()}関数を使いました。\texttt{everything()}という引数を含めているので、すべての変数に対し、全角文字を含んでいたら半角に直すというコードになります。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(stringi)}
\FunctionTok{read\_xlsx}\NormalTok{(}\StringTok{"data/ペンギン（ひどい列名）ver.xlsx"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{rename\_with}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\FunctionTok{stri\_trans\_nfkc}\NormalTok{(.),}
              \FunctionTok{everything}\NormalTok{())}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 344 x 9
##   Species `種 類`  `※島の名前` `1クチバシ 長さ(~ `2クチバシ_大き~
##   <chr>   <chr>    <chr>                   <dbl>            <dbl>
## 1 Adelie  アデリー Torgersen                39.1             18.7
## 2 Adelie  アデリー Torgersen                39.5             17.4
## 3 Adelie  アデリー Torgersen                40.3             18  
## # ... with 341 more rows, and 4 more variables:
## #   翼:長さ(mm) <dbl>, ■体重 単位はg <dbl>, 女男 <chr>,
## #   2007~2009 <dbl>
\end{verbatim}

\newpage

\hypertarget{ux4e0aux8a18ux306eux5408ux308fux305bux6280}{%
\subsubsection{上記の合わせ技}\label{ux4e0aux8a18ux306eux5408ux308fux305bux6280}}

\texttt{\%\textgreater{}\%} でつなぎ合わせて1つの実行で合わせてしまうこともできます。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{read\_xlsx}\NormalTok{(}\StringTok{"data/ペンギン（ひどい列名）ver.xlsx"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{rename\_with}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\FunctionTok{stri\_trans\_nfkc}\NormalTok{(.),}
              \FunctionTok{everything}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%} 
    \FunctionTok{clean\_names}\NormalTok{(}\AttributeTok{case =} \StringTok{"old\_janitor"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 344 x 9
##   species 種_類    x_島の名前 x1クチバシ_長さ_mm x2クチバシ_大き~
##   <chr>   <chr>    <chr>                   <dbl>            <dbl>
## 1 Adelie  アデリー Torgersen                39.1             18.7
## 2 Adelie  アデリー Torgersen                39.5             17.4
## 3 Adelie  アデリー Torgersen                40.3             18  
## # ... with 341 more rows, and 4 more variables:
## #   翼_長さ_mm <dbl>, x_体重_単位はg <dbl>, 女男 <chr>,
## #   x2007_2009 <dbl>
\end{verbatim}

\hypertarget{ux958bux59cbux884cux3092ux6307ux5b9aux3057ux3066ux8aadux307fux8fbcux3080}{%
\subsection{開始行を指定して読み込む}\label{ux958bux59cbux884cux3092ux6307ux5b9aux3057ux3066ux8aadux307fux8fbcux3080}}

理想的なデータは1行目に列名が入力されている形ですが、最初の数行が空だったり、文字の説明が入っていたりすることも多いです。そうした場合は、以下のような読み込み結果になります。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{read\_xlsx}\NormalTok{(}\StringTok{"data/ペンギン（3行空き）.xlsx"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{select}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{3}\NormalTok{) }\CommentTok{\# 紙面の都合のため最初の3列に制限}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 346 x 3
##   ...1    ここに説明とか書いてあるファイル読むのつら~ ...3       
##   <chr>   <chr>                                       <chr>      
## 1 <NA>    <NA>                                        <NA>       
## 2 species island                                      bill_lengt~
## 3 Adelie  Torgersen                                   39.1       
## # ... with 343 more rows
\end{verbatim}

列名が、セルに内容が入っている行から始まり、他の列名が\texttt{...1}, \texttt{...3}といったものになりました。そしてデータがうまく読み込めていません。これを、指定した行から読み込むには、引数\texttt{skip\ =}にとばしたい行の数を指定します。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{read\_xlsx}\NormalTok{(}\StringTok{"data/ペンギン（3行空き）.xlsx"}\NormalTok{, }\AttributeTok{skip =} \DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 344 x 9
##   species island    bill_length_mm bill_depth_mm flipper_length_~
##   <chr>   <chr>              <dbl>         <dbl>            <dbl>
## 1 Adelie  Torgersen           39.1          18.7              181
## 2 Adelie  Torgersen           39.5          17.4              186
## 3 Adelie  Torgersen           40.3          18                195
## # ... with 341 more rows, and 4 more variables:
## #   body_mass_g <dbl>, sex <chr>, year <dbl>, 種類 <chr>
\end{verbatim}

このように、ちゃんと読む込むことができました。

\hypertarget{ux30bbux30ebux3092ux6307ux5b9aux3057ux3066ux8aadux307fux8fbcux3080}{%
\subsection{セルを指定して読み込む}\label{ux30bbux30ebux3092ux6307ux5b9aux3057ux3066ux8aadux307fux8fbcux3080}}

引数\texttt{range\ =}にセル範囲を指定すれば、そのセル範囲だけを読み込むこともできます。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{read\_xlsx}\NormalTok{(}\StringTok{"data/ペンギン.xlsx"}\NormalTok{, }\AttributeTok{range =} \StringTok{"A1:D5"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 4 x 4
##   species 種類     island    bill_length_mm
##   <chr>   <chr>    <chr>              <dbl>
## 1 Adelie  アデリー Torgersen           39.1
## 2 Adelie  アデリー Torgersen           39.5
## 3 Adelie  アデリー Torgersen           40.3
## 4 Adelie  アデリー Torgersen           NA
\end{verbatim}

他にも、\texttt{cell\_cols\ =}で読みたい列の指定、\texttt{cell\_rows\ =}で読みたい行の指定も行えます。

詳細は、\texttt{?readxl}と打ち込んでヘルプを見るか、readxlの\href{https://readxl.tidyverse.org/}{webサイト} \footnote{\url{https://readxl.tidyverse.org/}}を参照してください。

\hypertarget{ux30b7ux30fcux30c8ux3092ux6307ux5b9aux3057ux3066ux8aadux307fux8fbcux3080}{%
\section{シートを指定して読み込む}\label{ux30b7ux30fcux30c8ux3092ux6307ux5b9aux3057ux3066ux8aadux307fux8fbcux3080}}

\hypertarget{ux30b7ux30fcux30c8ux540dux306eux78baux8a8d}{%
\subsection{シート名の確認}\label{ux30b7ux30fcux30c8ux540dux306eux78baux8a8d}}

複雑なExcelファイルとなると、たくさんのシートが含まれていて、その全容を知るのも一苦労です。Rでは、\texttt{readxl}パッケージの\texttt{excel\_sheets()}関数でシート名の一覧を簡単に取得できます。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{excel\_sheets}\NormalTok{(}\StringTok{"data/ペンギン（シート別）.xlsx"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "アデリー"   "ジェンツー" "ヒゲ"
\end{verbatim}

\hypertarget{ux666eux901aux306eux8aadux307fux8fbcux307f}{%
\subsection{普通の読み込み}\label{ux666eux901aux306eux8aadux307fux8fbcux307f}}

シートが分かれているExcelファイルをそのまま読みこんでみます。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{read\_xlsx}\NormalTok{(}\StringTok{"data/ペンギン（シート別）.xlsx"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 152 x 9
##   species 種類     island    bill_length_mm bill_depth_mm
##   <chr>   <chr>    <chr>              <dbl>         <dbl>
## 1 Adelie  アデリー Torgersen           39.1          18.7
## 2 Adelie  アデリー Torgersen           39.5          17.4
## 3 Adelie  アデリー Torgersen           40.3          18  
## # ... with 149 more rows, and 4 more variables:
## #   flipper_length_mm <dbl>, body_mass_g <dbl>, sex <chr>,
## #   year <dbl>
\end{verbatim}

デフォルトでは一番最初のシートのデータが読みこまれます。ここでは、シート「アデリー」が読み込まれました。

\hypertarget{ux30b7ux30fcux30c8ux3092ux6307ux5b9aux3057ux305fux8aadux307fux8fbcux307f}{%
\subsection{シートを指定した読み込み}\label{ux30b7ux30fcux30c8ux3092ux6307ux5b9aux3057ux305fux8aadux307fux8fbcux307f}}

引数の\texttt{sheet\ =}にシート名を指定することで読み込めます。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{read\_excel}\NormalTok{(}\StringTok{"data/ペンギン（シート別）.xlsx"}\NormalTok{, }\AttributeTok{sheet =} \StringTok{"ジェンツー"}\NormalTok{ )}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 124 x 9
##   species 種類       island bill_length_mm bill_depth_mm
##   <chr>   <chr>      <chr>           <dbl>         <dbl>
## 1 Gentoo  ジェンツー Biscoe           46.1          13.2
## 2 Gentoo  ジェンツー Biscoe           50            16.3
## 3 Gentoo  ジェンツー Biscoe           48.7          14.1
## # ... with 121 more rows, and 4 more variables:
## #   flipper_length_mm <dbl>, body_mass_g <dbl>, sex <chr>,
## #   year <dbl>
\end{verbatim}

\hypertarget{dflist}{%
\subsection{すべてのシートから一気に読み込み}\label{dflist}}

今まで身につけた知識を使うと、すべてのシートからデータを読みたいときは、単純に

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df\_Adelie }\OtherTok{\textless{}{-}} 
  \FunctionTok{read\_excel}\NormalTok{(}\StringTok{"data/ペンギン（シート別）.xlsx"}\NormalTok{, }\AttributeTok{sheet =} \StringTok{"アデリー"}\NormalTok{ )}
\NormalTok{df\_Gentoo }\OtherTok{\textless{}{-}} 
  \FunctionTok{read\_excel}\NormalTok{(}\StringTok{"data/ペンギン（シート別）.xlsx"}\NormalTok{, }\AttributeTok{sheet =} \StringTok{"ジェンツー"}\NormalTok{ )}
\NormalTok{df\_Chinstrap }\OtherTok{\textless{}{-}} 
  \FunctionTok{read\_excel}\NormalTok{(}\StringTok{"data/ペンギン（シート別）.xlsx"}\NormalTok{, }\AttributeTok{sheet =} \StringTok{"ヒゲ"}\NormalTok{ )}
\end{Highlighting}
\end{Shaded}

と１つずつ読み込めばよいとわかります。しかし、これが100シート分あったら読むだけで多くの時間がかかり、うんざりしてしまうでしょう。また、疲労によりミスも起こるかもしれません。コードも長くて読みにくくなってしまいます。そんな時に\textbf{便利で正確で短くコードが書ける}素敵な方法があるのです。おそらくこれを知って使えるようになることが、初心者から中級者への第一歩になるのではないでしょうか。

ここで\textbf{一気にレベルが上がり}ますが、これこそがRを使ってExcelファイルを読み込む便利な部分（その用途に限らず、コード書いてコンピュータに働いてもらうの最高！ってなる部分）なので、その魅力をみていきましょう。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{path\_name }\OtherTok{\textless{}{-}} \StringTok{"data/ペンギン（シート別）.xlsx"} \CommentTok{\# データのパスを格納}

\CommentTok{\# シート名を取得しそれぞれから読み込んでリストにまとめる}
\NormalTok{df\_list }\OtherTok{\textless{}{-}}
  \FunctionTok{excel\_sheets}\NormalTok{(path\_name) }\SpecialCharTok{\%\textgreater{}\%}                     
  \FunctionTok{set\_names}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}           \CommentTok{\# 名前付きベクトルにする}
  \FunctionTok{map}\NormalTok{(read\_excel, }\AttributeTok{path =}\NormalTok{  path\_name)}

\NormalTok{df\_list }\CommentTok{\# 作成したリストの表示}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $アデリー
## # A tibble: 152 x 9
##   species 種類     island    bill_length_mm bill_depth_mm
##   <chr>   <chr>    <chr>              <dbl>         <dbl>
## 1 Adelie  アデリー Torgersen           39.1          18.7
## 2 Adelie  アデリー Torgersen           39.5          17.4
## 3 Adelie  アデリー Torgersen           40.3          18  
## # ... with 149 more rows, and 4 more variables:
## #   flipper_length_mm <dbl>, body_mass_g <dbl>, sex <chr>,
## #   year <dbl>
## 
## $ジェンツー
## # A tibble: 124 x 9
##   species 種類       island bill_length_mm bill_depth_mm
##   <chr>   <chr>      <chr>           <dbl>         <dbl>
## 1 Gentoo  ジェンツー Biscoe           46.1          13.2
## 2 Gentoo  ジェンツー Biscoe           50            16.3
## 3 Gentoo  ジェンツー Biscoe           48.7          14.1
## # ... with 121 more rows, and 4 more variables:
## #   flipper_length_mm <dbl>, body_mass_g <dbl>, sex <chr>,
## #   year <dbl>
## 
## $ヒゲ
## # A tibble: 68 x 9
##   species   種類  island bill_length_mm bill_depth_mm
##   <chr>     <chr> <chr>           <dbl>         <dbl>
## 1 Chinstrap ヒゲ  Dream            46.5          17.9
## 2 Chinstrap ヒゲ  Dream            50            19.5
## 3 Chinstrap ヒゲ  Dream            51.3          19.2
## # ... with 65 more rows, and 4 more variables:
## #   flipper_length_mm <dbl>, body_mass_g <dbl>, sex <chr>,
## #   year <dbl>
\end{verbatim}

それぞれのExcelシートから読みこまれた3つのデータ（アデリー、ジェンツー、ヒゲ）はデータフレームとして、\texttt{df\_list}にリストと呼ばれる形式にてまとめて格納されています。リストは最初は理解が難しいですが、慣れるとなんでもリストにしたくなるくらい便利なものです。リストの中身を個別に取り出してみてみましょう。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df\_list}\SpecialCharTok{$}\NormalTok{ジェンツー}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 124 x 9
##   species 種類       island bill_length_mm bill_depth_mm
##   <chr>   <chr>      <chr>           <dbl>         <dbl>
## 1 Gentoo  ジェンツー Biscoe           46.1          13.2
## 2 Gentoo  ジェンツー Biscoe           50            16.3
## 3 Gentoo  ジェンツー Biscoe           48.7          14.1
## # ... with 121 more rows, and 4 more variables:
## #   flipper_length_mm <dbl>, body_mass_g <dbl>, sex <chr>,
## #   year <dbl>
\end{verbatim}

これは、\texttt{df\_list}というリストの中の、\texttt{ジェンツー}という要素（ここではデータフレーム）を取り出す、というコードです。\texttt{\$}が「（左側にくるオブジェクト）の中の」という意味を表しています。自分でコードを打つと、\texttt{df\_list\$}と打った時点で、中の要素の一覧が表示されるはずなので、そこからクリックして選ぶこともできます。

それでは、先ほど実行した読み込みコードの解説をします。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{path\_name }\OtherTok{\textless{}{-}} \StringTok{"data/ペンギン（シート別）.xlsx"}
\end{Highlighting}
\end{Shaded}

これは、単にファイルの場所を\texttt{path\_name}に格納しただけです。自分のデータで試してみたいときは、基本的にここのパス名を変えるだけで実行できるはずです。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df\_list }\OtherTok{\textless{}{-}}
  \FunctionTok{excel\_sheets}\NormalTok{(path\_name) }\SpecialCharTok{\%\textgreater{}\%}                    
  \FunctionTok{set\_names}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}                           
  \FunctionTok{map}\NormalTok{(read\_excel, }\AttributeTok{path =}\NormalTok{  path\_name) }
\end{Highlighting}
\end{Shaded}

\texttt{excel\_sheets()}は上で実行したのと同じです。実行結果はベクトルとして保存されています。\texttt{set\_names()}は、ベクトルを名前付きベクトルにする働きをします。なので、ここでできるのは、

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{excel\_sheets}\NormalTok{(path\_name) }\SpecialCharTok{\%\textgreater{}\%}                    
  \FunctionTok{set\_names}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     アデリー   ジェンツー         ヒゲ 
##   "アデリー" "ジェンツー"       "ヒゲ"
\end{verbatim}

です。

それぞれについて\texttt{purrr}パッケージの\texttt{map()}関数を使って\texttt{read\_excel()}を1つ1つのシート（ここでは作成した名前付きベクトルの要素）に適用していき、データを読み込みデータフレームにし、1つのリストにまとめるという作業をします。繰り返し似たような作業をするときに、この\texttt{map()}関数が非常に便利です。

\hypertarget{onedflist}{%
\subsubsection{一つのデータフレームにする}\label{onedflist}}

\texttt{bind\_rows()}は、データフレームを縦に連結します。データフレームがリストになったものが引数にくると、それらをすべて縦につなげてくれます。引数\texttt{.id\ =}で、リストの要素名を変数の値として入れることができるので、どのデータフレームから来たのか識別することが可能になります。ここでは\texttt{group}という名前にしています。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df\_all }\OtherTok{\textless{}{-}} 
  \FunctionTok{bind\_rows}\NormalTok{(df\_list, }\AttributeTok{.id =} \StringTok{"group"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{ux4f5cux6210ux3057ux305fux30c7ux30fcux30bfux30d5ux30ecux30fcux30e0ux306eux78baux8a8d}{%
\subsubsection{作成したデータフレームの確認}\label{ux4f5cux6210ux3057ux305fux30c7ux30fcux30bfux30d5ux30ecux30fcux30e0ux306eux78baux8a8d}}

最初の3行と最後の3行だけを表示してどんなものができたか確認します。\texttt{dplyr}パッケージの\texttt{slice\_head()}, \texttt{slice\_tail()}関数を使って、引数\texttt{n\ =}に表示したい行数を指定することで、最初および最後の数行を取得できます。

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 最初の3行}
\NormalTok{df\_all }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{slice\_head}\NormalTok{(}\AttributeTok{n =} \DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 3 x 10
##   group    species 種類     island   bill_length_mm bill_depth_mm
##   <chr>    <chr>   <chr>    <chr>             <dbl>         <dbl>
## 1 アデリー Adelie  アデリー Torgers~           39.1          18.7
## 2 アデリー Adelie  アデリー Torgers~           39.5          17.4
## 3 アデリー Adelie  アデリー Torgers~           40.3          18  
## # ... with 4 more variables: flipper_length_mm <dbl>,
## #   body_mass_g <dbl>, sex <chr>, year <dbl>
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 最後の3行}
\NormalTok{df\_all }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{slice\_tail}\NormalTok{(}\AttributeTok{n =} \DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 3 x 10
##   group species   種類  island bill_length_mm bill_depth_mm
##   <chr> <chr>     <chr> <chr>           <dbl>         <dbl>
## 1 ヒゲ  Chinstrap ヒゲ  Dream            49.6          18.2
## 2 ヒゲ  Chinstrap ヒゲ  Dream            50.8          19  
## 3 ヒゲ  Chinstrap ヒゲ  Dream            50.2          18.7
## # ... with 4 more variables: flipper_length_mm <dbl>,
## #   body_mass_g <dbl>, sex <chr>, year <dbl>
\end{verbatim}

一気にやるには\texttt{slice()}関数が便利です。\texttt{1:3}は1行目から3行目、\texttt{(n()-2):n()}は、列数（ただし現在のgroup内）を表す\texttt{n()}とそれから-2行した\texttt{(n()-2)}で表されています。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df\_all }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{slice}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{3}\NormalTok{, (}\FunctionTok{n}\NormalTok{()}\SpecialCharTok{{-}}\DecValTok{2}\NormalTok{)}\SpecialCharTok{:}\FunctionTok{n}\NormalTok{())}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 10
##   group    species   種類     island bill_length_mm bill_depth_mm
##   <chr>    <chr>     <chr>    <chr>           <dbl>         <dbl>
## 1 アデリー Adelie    アデリー Torge~           39.1          18.7
## 2 アデリー Adelie    アデリー Torge~           39.5          17.4
## 3 アデリー Adelie    アデリー Torge~           40.3          18  
## 4 ヒゲ     Chinstrap ヒゲ     Dream            49.6          18.2
## 5 ヒゲ     Chinstrap ヒゲ     Dream            50.8          19  
## 6 ヒゲ     Chinstrap ヒゲ     Dream            50.2          18.7
## # ... with 4 more variables: flipper_length_mm <dbl>,
## #   body_mass_g <dbl>, sex <chr>, year <dbl>
\end{verbatim}

\newpage

\hypertarget{readseveralexcel}{%
\section{複数のExcelファイルを読み込む}\label{readseveralexcel}}

それでは、さらにRの恩恵を深く実感できる部分に入ります。読みこみたいExcelファイルが大量にある場合です。これも実務上よく遭遇します。やり方としては、\ref{dflist}で使った方法とほぼ同じです。

ただし、ここでは読み込むファイルの構造がすべて同様の場合に限ります。残念ながら、それがかなわない状況に、現実ではたくさん遭遇します。いつか本書の応用編を書くことがあったら、そちらで解説することとして、今回は構造が単純な場合に限って解説します。

おそらく、単純に思いつく方法は、

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df\_Adelie    }\OtherTok{\textless{}{-}} \FunctionTok{read\_xlsx}\NormalTok{(}\StringTok{"data/複数/アデリー.xlsx"}\NormalTok{)}
\NormalTok{df\_Gentoo    }\OtherTok{\textless{}{-}} \FunctionTok{read\_xlsx}\NormalTok{(}\StringTok{"data/複数/ジェンツー.xlsx"}\NormalTok{)}
\NormalTok{df\_Chinstrap }\OtherTok{\textless{}{-}} \FunctionTok{read\_xlsx}\NormalTok{(}\StringTok{"data/複数/ヒゲ.xlsx"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

と1つずつ読んでいく方法ですが、これも大量にあったら泣きたくなる作業です。1つ1つファイル名を入力やコピペする間にいくらでもミスが生じます。\ref{hokan}で紹介した自動補完を使っても、楽しいのは最初だけでしょう。そこで、ファイルを指定するところから極力人の手を介さず進めていく方法を次に解説していきます。

\hypertarget{ux8aadux307fux8fbcux3080ux30d5ux30a1ux30a4ux30ebux540dux306eux4e00ux89a7ux306eux30aaux30d6ux30b8ux30a7ux30afux30c8ux4f5cux6210}{%
\subsection{読み込むファイル名の一覧のオブジェクト作成}\label{ux8aadux307fux8fbcux3080ux30d5ux30a1ux30a4ux30ebux540dux306eux4e00ux89a7ux306eux30aaux30d6ux30b8ux30a7ux30afux30c8ux4f5cux6210}}

まず、読み込みたいファイルが格納されているフォルダのファイル名、およびパス名の一覧を取得します。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{files }\OtherTok{\textless{}{-}}
    \FunctionTok{list.files}\NormalTok{(}\AttributeTok{path =} \StringTok{"data/複数/"}\NormalTok{, }\AttributeTok{full.names =} \ConstantTok{TRUE}\NormalTok{)}

\NormalTok{files}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "data/複数/アデリー.xlsx"   "data/複数/ジェンツー.xlsx"
## [3] "data/複数/ヒゲ.xlsx"       "data/複数/フォルダ1"      
## [5] "data/複数/フォルダ2"       "data/複数/フォルダ3"
\end{verbatim}

\texttt{list.files()}関数は、\texttt{path\ =}で指定したフォルダ内の情報を取得します。\texttt{full.names\ =\ TRUE}でパスも含めます。これをつけないと、ファイル名と拡張子だけの取得になります。

このうち、使用するのはxlsxファイルだけなので、文字列で該当するデータを取得する\texttt{str\_subset()}を用い、以下のように限定します。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{files }\OtherTok{\textless{}{-}} 
\NormalTok{  files }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{str\_subset}\NormalTok{(}\StringTok{"xlsx"}\NormalTok{)}

\NormalTok{files}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "data/複数/アデリー.xlsx"   "data/複数/ジェンツー.xlsx"
## [3] "data/複数/ヒゲ.xlsx"
\end{verbatim}

\hypertarget{ikkatsuread}{%
\subsection{ファイルを一括で読み込む}\label{ikkatsuread}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ldata }\OtherTok{\textless{}{-}}
    \FunctionTok{map}\NormalTok{(files, }\SpecialCharTok{\textasciitilde{}}\FunctionTok{read\_xlsx}\NormalTok{(.))}

\NormalTok{ldata}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [[1]]
## # A tibble: 152 x 9
##   species 種類     island    bill_length_mm bill_depth_mm
##   <chr>   <chr>    <chr>              <dbl>         <dbl>
## 1 Adelie  アデリー Torgersen           39.1          18.7
## 2 Adelie  アデリー Torgersen           39.5          17.4
## 3 Adelie  アデリー Torgersen           40.3          18  
## # ... with 149 more rows, and 4 more variables:
## #   flipper_length_mm <dbl>, body_mass_g <dbl>, sex <chr>,
## #   year <dbl>
## 
## [[2]]
## # A tibble: 124 x 9
##   species 種類       island bill_length_mm bill_depth_mm
##   <chr>   <chr>      <chr>           <dbl>         <dbl>
## 1 Gentoo  ジェンツー Biscoe           46.1          13.2
## 2 Gentoo  ジェンツー Biscoe           50            16.3
## 3 Gentoo  ジェンツー Biscoe           48.7          14.1
## # ... with 121 more rows, and 4 more variables:
## #   flipper_length_mm <dbl>, body_mass_g <dbl>, sex <chr>,
## #   year <dbl>
## 
## [[3]]
## # A tibble: 68 x 9
##   species   種類  island bill_length_mm bill_depth_mm
##   <chr>     <chr> <chr>           <dbl>         <dbl>
## 1 Chinstrap ヒゲ  Dream            46.5          17.9
## 2 Chinstrap ヒゲ  Dream            50            19.5
## 3 Chinstrap ヒゲ  Dream            51.3          19.2
## # ... with 65 more rows, and 4 more variables:
## #   flipper_length_mm <dbl>, body_mass_g <dbl>, sex <chr>,
## #   year <dbl>
\end{verbatim}

ここでできた\texttt{ldata}は、\ref{dflist}で作成した\texttt{df\_list}と同じ構造です。違いはそれぞれのデータフレームの要素名（アデリー、ジェンツー、ヒゲ）が入っていない点です。各要素の上の部分にある名前が\texttt{{[}{[}1{]}{]},\ {[}{[}3{]}{]},\ {[}{[}3{]}{]}}と表示されています（つまり、1, 2, 3の数値が割り当てられている）。要素名が入っていないのは不便なので、以下で要素名を改めてつけます。

\hypertarget{ux30d5ux30a1ux30a4ux30ebux540dux62bdux51fa}{%
\subsubsection{ファイル名抽出}\label{ux30d5ux30a1ux30a4ux30ebux540dux62bdux51fa}}

先ほど作成した\texttt{files}から、ファイル名部分だけに加工します。\texttt{str\_replace()}は、\texttt{stringr}パッケージの、文字の置換をする関数です。ここでは、拡張子とパス名をそれぞれ\texttt{""}、つまり空白に置換しています。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{file\_name }\OtherTok{\textless{}{-}} 
  \FunctionTok{str\_replace}\NormalTok{(files, }\StringTok{".xlsx"}\NormalTok{, }\StringTok{""}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{str\_replace}\NormalTok{(}\StringTok{"data/複数/"}\NormalTok{, }\StringTok{""}\NormalTok{)}

\NormalTok{file\_name}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "アデリー"   "ジェンツー" "ヒゲ"
\end{verbatim}

\hypertarget{ux30eaux30b9ux30c8ux306eux8981ux7d20ux540dux306bux30d5ux30a1ux30a4ux30ebux540dux3092ux4ed8ux4e0e}{%
\subsubsection{リストの要素名にファイル名を付与}\label{ux30eaux30b9ux30c8ux306eux8981ux7d20ux540dux306bux30d5ux30a1ux30a4ux30ebux540dux3092ux4ed8ux4e0e}}

\ref{dflist}で使った\texttt{set\_names()}関数は、リストの要素名を付ける時にも使えます。リスト\texttt{ldata}の3つの要素に、\texttt{file\_name}の中身を割り当てます。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ldata }\OtherTok{\textless{}{-}}
    \FunctionTok{set\_names}\NormalTok{(ldata, file\_name)}

\NormalTok{ldata}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $アデリー
## # A tibble: 152 x 9
##   species 種類     island    bill_length_mm bill_depth_mm
##   <chr>   <chr>    <chr>              <dbl>         <dbl>
## 1 Adelie  アデリー Torgersen           39.1          18.7
## 2 Adelie  アデリー Torgersen           39.5          17.4
## 3 Adelie  アデリー Torgersen           40.3          18  
## # ... with 149 more rows, and 4 more variables:
## #   flipper_length_mm <dbl>, body_mass_g <dbl>, sex <chr>,
## #   year <dbl>
## 
## $ジェンツー
## # A tibble: 124 x 9
##   species 種類       island bill_length_mm bill_depth_mm
##   <chr>   <chr>      <chr>           <dbl>         <dbl>
## 1 Gentoo  ジェンツー Biscoe           46.1          13.2
## 2 Gentoo  ジェンツー Biscoe           50            16.3
## 3 Gentoo  ジェンツー Biscoe           48.7          14.1
## # ... with 121 more rows, and 4 more variables:
## #   flipper_length_mm <dbl>, body_mass_g <dbl>, sex <chr>,
## #   year <dbl>
## 
## $ヒゲ
## # A tibble: 68 x 9
##   species   種類  island bill_length_mm bill_depth_mm
##   <chr>     <chr> <chr>           <dbl>         <dbl>
## 1 Chinstrap ヒゲ  Dream            46.5          17.9
## 2 Chinstrap ヒゲ  Dream            50            19.5
## 3 Chinstrap ヒゲ  Dream            51.3          19.2
## # ... with 65 more rows, and 4 more variables:
## #   flipper_length_mm <dbl>, body_mass_g <dbl>, sex <chr>,
## #   year <dbl>
\end{verbatim}

このように、ちゃんと要素に名前が付きました。これらを1つのデータフレームにまとめるには、 \ref{onedflist}と同じ手順でできます。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{bind\_rows}\NormalTok{(ldata, }\AttributeTok{.id =} \StringTok{"group"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{ux8aadux307fux8fbcux3080ux30d5ux30a1ux30a4ux30ebux304cux8907ux6570ux30d5ux30a9ux30ebux30c0ux306bux3042ux308bux5834ux5408}{%
\subsection{読み込むファイルが複数フォルダにある場合}\label{ux8aadux307fux8fbcux3080ux30d5ux30a1ux30a4ux30ebux304cux8907ux6570ux30d5ux30a9ux30ebux30c0ux306bux3042ux308bux5834ux5408}}

\texttt{data/複数}フォルダの中に、さらにフォルダ1～フォルダ3がありました。この中にもそれぞれxlsxファイルが入っていて、それぞれ読み込みたいとします。その場合は、先ほど使った\texttt{list.files()}関数の引数、\texttt{recursive\ =\ TRUE}を追加します。これによって、フォルダの深い階層までもすべて読み込むことが可能になります。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{files }\OtherTok{\textless{}{-}}
    \FunctionTok{list.files}\NormalTok{(}\AttributeTok{path =} \StringTok{"data/複数/"}\NormalTok{, }\AttributeTok{full.names =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{recursive =} \ConstantTok{TRUE}\NormalTok{)}

\NormalTok{files}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "data/複数//フォルダ1/アデリー.xlsx"  
## [2] "data/複数//フォルダ2/ジェンツー.xlsx"
## [3] "data/複数//フォルダ3/ヒゲ.xlsx"      
## [4] "data/複数/アデリー.xlsx"             
## [5] "data/複数/ジェンツー.xlsx"           
## [6] "data/複数/ヒゲ.xlsx"
\end{verbatim}

このうち、使用するのはフォルダ1～3に入っているxlsxファイルだけなので、\texttt{str\_subset()}関数で以下のように絞り込みます。ここの\texttt{""}の中に入る文字列がどうなるかが難しいところかもしれませんが、ここは正規表現という本書の範囲を超える世界なので、深入りはしません。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{files }\OtherTok{\textless{}{-}} 
\NormalTok{  files }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{str\_subset}\NormalTok{(}\StringTok{"フォルダ"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

あとは\ref{ikkatsuread}と同じ手順で読み込めます。

\hypertarget{writeexcel}{%
\chapter{Excelファイルの保存}\label{writeexcel}}

\hypertarget{writeoneexcel}{%
\section{一つのExcelファイルを保存する}\label{writeoneexcel}}

\texttt{writexl}パッケージの\texttt{write\_xlsx()}関数で、直接Excelファイルとして出力ができます。ここでは、新しく作成したデータフレームをExcelファイルとして保存してみます。

\hypertarget{groupbymean}{%
\subsection{カテゴリ別平均値の作成}\label{groupbymean}}

クチバシの長さと大きさを表す変数である、\texttt{bill\_length\_mm}、\texttt{bill\_depth\_mm}について、平均値と欠損を抜いたn（ペンギン数）を種類別に計算します。\texttt{group\_by()}でカテゴリ別にしたい変数を指定し、\texttt{summarise()}で平均値とnを計算するコードが以下になります。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df\_group\_mean }\OtherTok{\textless{}{-}} 
\NormalTok{  df }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(種類) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\FunctionTok{across}\NormalTok{(}
                   \FunctionTok{c}\NormalTok{(bill\_length\_mm, bill\_depth\_mm), }\CommentTok{\# ここに変数}
                   \FunctionTok{list}\NormalTok{(}\AttributeTok{m =} \SpecialCharTok{\textasciitilde{}}\FunctionTok{mean}\NormalTok{(., }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),  }\CommentTok{\# 平均値計算}
                        \AttributeTok{n =} \SpecialCharTok{\textasciitilde{}}\FunctionTok{sum}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(.))))        }\CommentTok{\# 欠損のない人数計算}
\NormalTok{           )}

\CommentTok{\# ここは結果の整形部分}
\NormalTok{df\_group\_mean }\OtherTok{\textless{}{-}} 
\NormalTok{  df\_group\_mean }\SpecialCharTok{\%\textgreater{}\%}  
  \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{bill\_depth\_mm\_n) }\SpecialCharTok{\%\textgreater{}\%}  \CommentTok{\# nが同じなので列削除}
  \FunctionTok{rename}\NormalTok{(}\AttributeTok{n =}\NormalTok{ bill\_length\_mm\_n)  }\CommentTok{\# 列名をnにリネーム}


\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(df\_group\_mean) }\CommentTok{\# きれいな出力にするコード}
\end{Highlighting}
\end{Shaded}

\begin{tabular}{l|r|r|r}
\hline
種類 & bill\_length\_mm\_m & n & bill\_depth\_mm\_m\\
\hline
アデリー & 38.79139 & 151 & 18.34636\\
\hline
ジェンツー & 47.50488 & 123 & 14.98211\\
\hline
ヒゲ & 48.83382 & 68 & 18.42059\\
\hline
\end{tabular}

なお、ここで\texttt{knitr::kable()}という書き方が出てきますが、これは\texttt{knitr}パッケージの\texttt{kable()}関数という意味です。関数を1回しか使わない場合などに\texttt{library()}で呼び出すのは無駄が多かったりするので、時々こういった記述が出てきます。

\hypertarget{excelux30d5ux30a1ux30a4ux30ebux306eux4fddux5b58}{%
\subsection{Excelファイルの保存}\label{excelux30d5ux30a1ux30a4ux30ebux306eux4fddux5b58}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(writexl)}
\end{Highlighting}
\end{Shaded}

前節で作成したカテゴリ別平均値のデータフレーム\texttt{df\_group\_mean}をExcelファイルとして保存します。保存は\texttt{write\_xlsx()}関数の中に、データフレームのオブジェクトと出力先のパスと保存ファイル名を入れるだけです。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{write\_xlsx}\NormalTok{(df\_group\_mean, }\StringTok{"out/種類別平均値.xlsx"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\texttt{out/}の部分が出力先のフォルダを示しています。

\hypertarget{ux5fdcux7528ux30d5ux30a1ux30a4ux30ebux540dux306bux81eaux52d5ux3067ux672cux65e5ux306eux65e5ux4ed8ux3092ux5165ux308cux308b}{%
\subsubsection{【応用】ファイル名に自動で本日の日付を入れる}\label{ux5fdcux7528ux30d5ux30a1ux30a4ux30ebux540dux306bux81eaux52d5ux3067ux672cux65e5ux306eux65e5ux4ed8ux3092ux5165ux308cux308b}}

これはちょっと応用技ですが、便利なので紹介しておきます。\texttt{lubridate}パッケージの\texttt{today()}関数で、今日の日付を表示できるので、それを保存名を入れる時に組み込む（文字列なので区切って\texttt{str\_c()}でくっつける）と、日付入りファイル名が作成できます。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{write\_xlsx}\NormalTok{(df\_group\_mean, }
         \FunctionTok{str\_c}\NormalTok{(}\StringTok{"out/df\_group\_mean"}\NormalTok{, }\StringTok{"\_"}\NormalTok{, lubridate}\SpecialCharTok{::}\FunctionTok{today}\NormalTok{(), }\StringTok{".xlsx"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\hypertarget{writeseveralexcel}{%
\section{複数のファイルを一度に保存する}\label{writeseveralexcel}}

これが活躍する場面としては、たとえばカテゴリ別（例：ペンギンの種類別、会社の部署別など）に集計した要約値をそのカテゴリ別に個々のExcelファイルにするといった状況が思いつきますので、それをやってみます。

\hypertarget{splitdf}{%
\subsection{データフレームをカテゴリ別に分割してリストにする}\label{splitdf}}

\texttt{split()}関数を使うことで、カテゴリ別にデータフレームを分割し、リストにまとめた結果を作成できます。データは\ref{groupbymean}で作成した\texttt{df\_group\_mean}を使います。

分割に使う変数は、\texttt{df\_group\_mean\$species}のように、データフレーム名の後に\texttt{\$}をつけてその後に指定します。この変数の中身が、そのままリストの要素名になるので、後の処理がとても楽になります。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df\_gmean\_list }\OtherTok{\textless{}{-}} 
  \FunctionTok{split}\NormalTok{(df\_group\_mean, df\_group\_mean}\SpecialCharTok{$}\NormalTok{種類)}

\NormalTok{df\_gmean\_list}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $アデリー
## # A tibble: 1 x 4
##   種類     bill_length_mm_m     n bill_depth_mm_m
##   <chr>               <dbl> <int>           <dbl>
## 1 アデリー             38.8   151            18.3
## 
## $ジェンツー
## # A tibble: 1 x 4
##   種類       bill_length_mm_m     n bill_depth_mm_m
##   <chr>                 <dbl> <int>           <dbl>
## 1 ジェンツー             47.5   123            15.0
## 
## $ヒゲ
## # A tibble: 1 x 4
##   種類  bill_length_mm_m     n bill_depth_mm_m
##   <chr>            <dbl> <int>           <dbl>
## 1 ヒゲ              48.8    68            18.4
\end{verbatim}

\hypertarget{ux30eaux30b9ux30c8ux306eux5404ux8981ux7d20ux3092ux500bux5225ux3067excelux30d5ux30a1ux30a4ux30ebux306bux4fddux5b58ux3059ux308b}{%
\subsection{リストの各要素を個別でExcelファイルに保存する}\label{ux30eaux30b9ux30c8ux306eux5404ux8981ux7d20ux3092ux500bux5225ux3067excelux30d5ux30a1ux30a4ux30ebux306bux4fddux5b58ux3059ux308b}}

\texttt{purrr}パッケージの\texttt{imap()}関数を使って、リスト内の各データフレームに、それぞれの要素名をファイル名として、Excelファイルに出力します。

ここでは、リスト内の各要素を示すのが\texttt{.x}、要素名（位置）に当たるのは\texttt{.y}です。次々に代わるファイル名を作るのに、\texttt{str\_c()}関数で文字列を結合しています。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{imap}\NormalTok{(df\_gmean\_list, }\SpecialCharTok{\textasciitilde{}}\FunctionTok{write\_xlsx}\NormalTok{(.x, }\AttributeTok{path =} \FunctionTok{str\_c}\NormalTok{(}\StringTok{"out/"}\NormalTok{, .y , }\StringTok{".xlsx"}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\hypertarget{ux30b5ux30f3ux30d7ux30ebux30c7ux30fcux30bfux30bbux30c3ux30c8ux4f5cux6210ux30b3ux30fcux30c9}{%
\subsubsection{サンプルデータセット作成コード}\label{ux30b5ux30f3ux30d7ux30ebux30c7ux30fcux30bfux30bbux30c3ux30c8ux4f5cux6210ux30b3ux30fcux30c9}}

ちなみに\texttt{data/複数/}フォルダにあるサンプルデータセットは以下のコードで作りました。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{imap}\NormalTok{(df\_list, }\SpecialCharTok{\textasciitilde{}}\FunctionTok{write\_xlsx}\NormalTok{(.x, }\AttributeTok{path =} \FunctionTok{str\_c}\NormalTok{(}\StringTok{"data/複数/"}\NormalTok{,.y , }\StringTok{".xlsx"}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\hypertarget{ux4e00ux3064ux306eux30d5ux30a1ux30a4ux30ebux306eux8907ux6570ux30b7ux30fcux30c8ux306bux4fddux5b58ux3059ux308b}{%
\subsection{一つのファイルの複数シートに保存する}\label{ux4e00ux3064ux306eux30d5ux30a1ux30a4ux30ebux306eux8907ux6570ux30b7ux30fcux30c8ux306bux4fddux5b58ux3059ux308b}}

\ref{splitdf}で作成した、ペンギンの種類別クチバシの長さと大きさ平均値のデータを、個別のファイルでなく、一ファイルの複数シートに保存したいときは、とてもシンプルなコードで可能になります。

要素名のついたデータフレームのリストが作成されていれば、それを単純に\texttt{write\_xlsx()}で出力するだけで完成します。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{write\_xlsx}\NormalTok{(df\_gmean\_list, }\StringTok{"data/平均値（複数シート）.xlsx"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{readsavecsv}{%
\chapter{csvファイルの読み込みと保存}\label{readsavecsv}}

windows環境で過ごしていて日本語を使うRユーザーにおいては、csvファイルを扱う際に文字コードの違いというつらみ（いわゆる文字化け）に遭遇することが少なくありません。

出会う可能性が高い文字コードには、大きく\texttt{cp932（Shift-JIS）}と\texttt{UTF-8}という形式があり、一般的に業務で読みこもうとするファイルは前者であることが多いことを知っておくと役に立ちます。

\hypertarget{ux4e00ux3064ux306ecsvux30d5ux30a1ux30a4ux30ebux3092ux8aadux307fux8fbcux3080}{%
\section{一つのcsvファイルを読み込む}\label{ux4e00ux3064ux306ecsvux30d5ux30a1ux30a4ux30ebux3092ux8aadux307fux8fbcux3080}}

csvファイルを読みこむには、\texttt{readr}パッケージの\texttt{read\_csv()}関数を使います。\texttt{tidyverse}を読み込んだら一緒に読み込まれます。\texttt{readr}では基本的に\texttt{utf8}の読み書きが想定されています。RStudioのメニューで以下の部分をUTF-8に変えておかないと、色々つらい思いをします。

\begin{itemize}
\tightlist
\item
  \texttt{Tools\ \textgreater{}\ Global\ Options\ \textgreater{}\ Code\ \textgreater{}\ Saving\ \textgreater{}\ Default\ text\ encoding:}
\item
  \texttt{Tools\ \textgreater{}\ Project\ Options\ \textgreater{}\ Code\ Editing\ \textgreater{}\ text\ encoding:}
\end{itemize}

\texttt{data\ \textgreater{}\ csv}フォルダ（ここでは\texttt{\textgreater{}}は階層関係を示し、コードでは\texttt{data/csv/}で表現）に入っている「ペンギン（ひどい列名）ver\_utf8.csv」を開きます。\texttt{㊛㊚}列のみ、環境依存文字のため、csvにする時点で文字化けています\ldots{}

\hypertarget{utf-8ux3067ux30a8ux30f3ux30b3ux30fcux30c9ux3055ux308cux305fcsvux30d5ux30a1ux30a4ux30eb}{%
\subsection{UTF-8でエンコードされたcsvファイル}\label{utf-8ux3067ux30a8ux30f3ux30b3ux30fcux30c9ux3055ux308cux305fcsvux30d5ux30a1ux30a4ux30eb}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df\_csv }\OtherTok{\textless{}{-}} 
 \FunctionTok{read\_csv}\NormalTok{(}\StringTok{"data/csv/ペンギン（ひどい列名）ver\_utf8.csv"}\NormalTok{)}

\NormalTok{df\_csv}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 344 x 9
##   Sｐｅｃｉｅｓ `種　類` `※島の名前` `①クチバシ　長さ（ｍｍ）`
##   <chr>         <chr>    <chr>                           <dbl>
## 1 Adelie        アデリー Torgersen                        39.1
## 2 Adelie        アデリー Torgersen                        39.5
## 3 Adelie        アデリー Torgersen                        40.3
## # ... with 341 more rows, and 5 more variables:
## #   ②ｸﾁﾊﾞｼ＿大きさ（ｍｍ） <dbl>, 翼：長さ(mm) <dbl>,
## #   ■体重　単位はｇ <dbl>, <U+329B><U+329A> <chr>, ２００７～２００９ <dbl>
\end{verbatim}

\hypertarget{ux6587ux5b57ux5316ux3051ux306eux4f8bshift-jisux3067ux30a8ux30f3ux30b3ux30fcux30c9ux3055ux308cux305fcsvux30d5ux30a1ux30a4ux30eb}{%
\subsection{【文字化けの例】Shift-JISでエンコードされたcsvファイル}\label{ux6587ux5b57ux5316ux3051ux306eux4f8bshift-jisux3067ux30a8ux30f3ux30b3ux30fcux30c9ux3055ux308cux305fcsvux30d5ux30a1ux30a4ux30eb}}

正確にはShift-JISの拡張版であるcp932でエンコードされたファイルです。変数名も文字化けして読みこみ自体できなくなるので、\texttt{clean\_names()}で読める形式に変換しています。

日本語の変数名と、2列目の日本語の値が文字化けします。

\hypertarget{shift-jisux3067ux30a8ux30f3ux30b3ux30fcux30c9ux3055ux308cux305fcsvux30d5ux30a1ux30a4ux30eb}{%
\subsection{Shift-JISでエンコードされたcsvファイル}\label{shift-jisux3067ux30a8ux30f3ux30b3ux30fcux30c9ux3055ux308cux305fcsvux30d5ux30a1ux30a4ux30eb}}

これを読むためには，引数\texttt{locale\ =\ locale(encoding\ =\ )}でShift-JISのファイルであることを指定する必要があります。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{read\_csv}\NormalTok{(}\StringTok{"data/csv/ペンギン（ひどい列名）ver\_cp932.csv"}
\NormalTok{         , }\AttributeTok{locale =} \FunctionTok{locale}\NormalTok{(}\AttributeTok{encoding =} \StringTok{"cp932"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 344 x 9
##   Sｐｅｃｉｅｓ `種　類` `※島の名前` `①クチバシ　長さ（ｍｍ）`
##   <chr>         <chr>    <chr>                           <dbl>
## 1 Adelie        アデリー Torgersen                        39.1
## 2 Adelie        アデリー Torgersen                        39.5
## 3 Adelie        アデリー Torgersen                        40.3
## # ... with 341 more rows, and 5 more variables:
## #   ②ｸﾁﾊﾞｼ＿大きさ（ｍｍ） <dbl>, 翼：長さ(mm) <dbl>,
## #   ■体重　単位はｇ <dbl>, ?? <chr>, ２００７～２００９ <dbl>
\end{verbatim}

\newpage

\hypertarget{read.csvux3092ux4f7fux3046ux5834ux5408}{%
\subsection{read.csv()を使う場合}\label{read.csvux3092ux4f7fux3046ux5834ux5408}}

従来のcsvを読む関数\texttt{read.csv()}を使えば，デフォルトでShift-JISのファイルは読めます。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{read.csv}\NormalTok{(}\StringTok{"data/csv/ペンギン（ひどい列名）ver\_cp932.csv"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{as\_tibble}\NormalTok{()  }\CommentTok{\# データフレームをtibble型にし見やすい出力に}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 344 x 9
##   Sｐｅｃｉｅｓ 種.類    X.島の名前 X.クチバシ.長さ.ｍｍ.
##   <chr>         <chr>    <chr>                      <dbl>
## 1 Adelie        アデリー Torgersen                   39.1
## 2 Adelie        アデリー Torgersen                   39.5
## 3 Adelie        アデリー Torgersen                   40.3
## # ... with 341 more rows, and 5 more variables:
## #   X.ｸﾁﾊﾞｼ.大きさ.ｍｍ. <dbl>, 翼.長さ.mm. <int>,
## #   X.体重.単位はｇ <int>, X.. <chr>, ２００７.２００９ <int>
\end{verbatim}

UTF-8を読む場合は引数\texttt{encoding\ =}で指定します。が、列名がひどすぎたせいかちゃんと読めないので出力はスキップします\ldots{}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{read.csv}\NormalTok{(}\StringTok{"data/csv/ペンギン（ひどい列名）ver\_utf8.csv"}\NormalTok{, }
         \AttributeTok{encoding =} \StringTok{"UTF{-}8"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
    \FunctionTok{as\_tibble}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\hypertarget{ux5927ux304dux3044ux30c7ux30fcux30bfux306aux3089fread}{%
\subsection{大きいデータならfread()}\label{ux5927ux304dux3044ux30c7ux30fcux30bfux306aux3089fread}}

これまで紹介したcsvファイルを読みこむための関数は、小規模なデータならそんなに時間はかかりませんが、データが数万行×数百列と大きくなってくると、時間がかかるようになります。

そこで大きく時間を短縮できるのが、\texttt{data.table}パッケージの\texttt{fread()}関数です。実は筆者が一番使ってるのはこの関数です。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data.table}\SpecialCharTok{::}\FunctionTok{fread}\NormalTok{(}\StringTok{"data/csv/ペンギン（ひどい列名）ver\_cp932.csv"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{as\_tibble}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 344 x 9
##   Sｐｅｃｉｅｓ `種　類` `※島の名前` `①クチバシ　長さ（ｍｍ）`
##   <chr>         <chr>    <chr>                           <dbl>
## 1 Adelie        アデリー Torgersen                        39.1
## 2 Adelie        アデリー Torgersen                        39.5
## 3 Adelie        アデリー Torgersen                        40.3
## # ... with 341 more rows, and 5 more variables:
## #   ②ｸﾁﾊﾞｼ＿大きさ（ｍｍ） <dbl>, 翼：長さ(mm) <int>,
## #   ■体重　単位はｇ <int>, ?? <chr>, ２００７～２００９ <int>
\end{verbatim}

なお、UTF-8でエンコーディングされたcsvファイルの場合は、引数に\texttt{encoding\ =\ "UTF-8"}を加えることで読み込めます。

\hypertarget{writeonecsv}{%
\section{csvファイルの保存}\label{writeonecsv}}

csvファイルを保存するには、\texttt{readr}パッケージの\texttt{write\_csv()}関数を使います。ただし、出力されたcsvファイルをExcelで開くとたぶん文字化けします。LibreOfficeのCalcであれば、最初にダイアログボックスが開いて読む文字コードを選べます。

\hypertarget{write_csvux3092ux4f7fux3046}{%
\subsection{write\_csv()を使う}\label{write_csvux3092ux4f7fux3046}}

先ほど読みこんだ\texttt{df\_csv}と、保存先を\texttt{""}中に指定します。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{write\_csv}\NormalTok{(df\_csv, }\StringTok{"out/df\_csv\_utf8.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\newpage

\hypertarget{excelux3067ux958bux3044ux3066ux3082ux8aadux3081ux308bux3088ux3046ux306b}{%
\subsubsection{Excelで開いても読めるように}\label{excelux3067ux958bux3044ux3066ux3082ux8aadux3081ux308bux3088ux3046ux306b}}

Excelで開いても読める、BOM（byte order mark, バイトオーダーマーク）付きファイルとして出力する関数です。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{write\_excel\_csv}\NormalTok{(df\_csv, }\StringTok{"out/df\_csv\_utf8\_forxl.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{write.csvux3092ux4f7fux3046}{%
\subsection{write.csv()を使う}\label{write.csvux3092ux4f7fux3046}}

書き込みが遅いですが、文字化け回避の最終手段として、なぜかうまくいく時があるので、\texttt{write.csv()}も役に立ちます。Rでデフォルトの文字エンコードがcp932で、そちらを採用するからと思われます。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{write.csv}\NormalTok{(df\_csv, }\StringTok{"out/df\_csv\_cp932.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{dataanal}{%
\chapter{データ解析に向けて}\label{dataanal}}

ここまでの解説で、Excelファイルとcsvファイルの読み込みについて一通り解説してきました。この段階では、まだデータがきれいでなくて、解析に入れないことも多いと思います。

\hypertarget{ux8981ux7d04ux5024ux3084ux6b20ux640dux30c7ux30fcux30bfux306eux78baux8a8d}{%
\section{要約値や欠損データの確認}\label{ux8981ux7d04ux5024ux3084ux6b20ux640dux30c7ux30fcux30bfux306eux78baux8a8d}}

まずどんなデータがどのように入っているか、欠損値（NA）はどれくらい発生しているか確認することは重要なプロセスです。変数の一覧を要約して確認することが簡単にできる\texttt{skim}パッケージの\texttt{skimr()}関数を使って確認してみましょう。データは\ref{junbiyomikomi}で読み込んだ\texttt{df}を使います。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(skimr) }\CommentTok{\# version 2.1.2}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{skim}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}



データの型が数値である変数（ここでは\texttt{Variable\ type:numeric}）については、\texttt{hist}列に簡単なヒストグラムが表示されます（図\ref{fig:skim}）。しかしデータが大量な場合、動作が遅くなります。その場合は、ヒストグラムを描かない以下の関数が使えます。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{skim\_without\_charts}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\hypertarget{ux7d50ux679cux3092excelux30d5ux30a1ux30a4ux30ebux306bux51faux529bux3059ux308b}{%
\subsection{結果をExcelファイルに出力する}\label{ux7d50ux679cux3092excelux30d5ux30a1ux30a4ux30ebux306bux51faux529bux3059ux308b}}

\texttt{as\_tibble()}関数を使うことで、結果を一つのデータフレームにまとめることができます。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{res\_skim\_df }\OtherTok{\textless{}{-}} 
\FunctionTok{skim}\NormalTok{(df) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{as\_tibble}\NormalTok{()}

\NormalTok{res\_skim\_df }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{head}\NormalTok{()        }\CommentTok{\# 最初の6行を表示}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 17
##   skim_type skim_variable  n_missing complete_rate character.min
##   <chr>     <chr>              <int>         <dbl>         <int>
## 1 character species                0         1                 6
## 2 character 種類                   0         1                 2
## 3 character island                 0         1                 5
## 4 character sex                   11         0.968             4
## 5 numeric   bill_length_mm         2         0.994            NA
## 6 numeric   bill_depth_mm          2         0.994            NA
## # ... with 12 more variables: character.max <int>,
## #   character.empty <int>, character.n_unique <int>,
## #   character.whitespace <int>, numeric.mean <dbl>,
## #   numeric.sd <dbl>, numeric.p0 <dbl>, numeric.p25 <dbl>,
## #   numeric.p50 <dbl>, numeric.p75 <dbl>, numeric.p100 <dbl>,
## #   numeric.hist <chr>
\end{verbatim}

これで好きなように加工してExcelファイルとして出力することが可能になります。例えば、数値変数だけに絞る場合は

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{res\_skim\_df }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(skim\_type  }\SpecialCharTok{==} \StringTok{"numeric"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{select}\NormalTok{(skim\_type, skim\_variable,}
\NormalTok{         n\_missing, numeric.mean, numeric.sd)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 5 x 5
##   skim_type skim_variable     n_missing numeric.mean numeric.sd
##   <chr>     <chr>                 <int>        <dbl>      <dbl>
## 1 numeric   bill_length_mm            2         43.9      5.46 
## 2 numeric   bill_depth_mm             2         17.2      1.97 
## 3 numeric   flipper_length_mm         2        201.      14.1  
## 4 numeric   body_mass_g               2       4202.     802.   
## 5 numeric   year                      0       2008.       0.818
\end{verbatim}

また、\texttt{group\_by()}を使ってグループ別に上記結果を出すことも可能です。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{res\_df\_num\_g }\OtherTok{\textless{}{-}} 
\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(種類) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{skim}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{as\_tibble}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(skim\_type  }\SpecialCharTok{==} \StringTok{"numeric"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{select}\NormalTok{(skim\_type, skim\_variable, 種類,}
\NormalTok{         n\_missing, numeric.mean, numeric.sd)}

\NormalTok{res\_df\_num\_g}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 15 x 6
##    skim_type skim_variable     種類       n_missing numeric.mean
##    <chr>     <chr>             <chr>          <int>        <dbl>
##  1 numeric   bill_length_mm    アデリー           1         38.8
##  2 numeric   bill_length_mm    ジェンツー         1         47.5
##  3 numeric   bill_length_mm    ヒゲ               0         48.8
##  4 numeric   bill_depth_mm     アデリー           1         18.3
##  5 numeric   bill_depth_mm     ジェンツー         1         15.0
##  6 numeric   bill_depth_mm     ヒゲ               0         18.4
##  7 numeric   flipper_length_mm アデリー           1        190. 
##  8 numeric   flipper_length_mm ジェンツー         1        217. 
##  9 numeric   flipper_length_mm ヒゲ               0        196. 
## 10 numeric   body_mass_g       アデリー           1       3701. 
## 11 numeric   body_mass_g       ジェンツー         1       5076. 
## 12 numeric   body_mass_g       ヒゲ               0       3733. 
## 13 numeric   year              アデリー           0       2008. 
## 14 numeric   year              ジェンツー         0       2008. 
## 15 numeric   year              ヒゲ               0       2008. 
## # ... with 1 more variable: numeric.sd <dbl>
\end{verbatim}

あとは、以下のように出力するだけです。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{write\_xlsx}\NormalTok{(res\_df\_num\_g, }\StringTok{"out/種類別平均値（全数値型変数）.xlsx"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{ux53efux8996ux5316}{%
\subsection{可視化}\label{ux53efux8996ux5316}}

さらに\texttt{ggplot2}を使って可視化することも可能になります。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{res\_df\_num\_g }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(skim\_variable }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"bill\_length\_mm"}\NormalTok{, }\StringTok{"bill\_depth\_mm"}\NormalTok{,}
                             \StringTok{"flipper\_length\_mm"}\NormalTok{, }\StringTok{"body\_mass\_g"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ 種類, }\AttributeTok{y =}\NormalTok{ numeric.mean, }\AttributeTok{fill =}\NormalTok{ 種類)) }\SpecialCharTok{+}
   \FunctionTok{geom\_col}\NormalTok{() }\SpecialCharTok{+}
    \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{size =} \DecValTok{5}\NormalTok{)) }\SpecialCharTok{+}
   \FunctionTok{facet\_wrap}\NormalTok{(}\FunctionTok{vars}\NormalTok{(skim\_variable), }\AttributeTok{scale =} \StringTok{"free"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{gisho12_files/figure-latex/unnamed-chunk-61-1.pdf}

ただし、ここの場合もっと潤沢な可視化グラフは元データから作成できます。例えば

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{select}\NormalTok{(種類, bill\_length\_mm, bill\_depth\_mm, flipper\_length\_mm,}
\NormalTok{         body\_mass\_g) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{pivot\_longer}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{種類,                  }\CommentTok{\# wideデータからlongデータに変換}
               \AttributeTok{names\_to =} \StringTok{"variables"}\NormalTok{,}
               \AttributeTok{values\_to =} \StringTok{"scores"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ 種類, }\AttributeTok{y =}\NormalTok{ scores, }\AttributeTok{fill =}\NormalTok{ 種類)) }\SpecialCharTok{+}
   \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.3}\NormalTok{, }\AttributeTok{width =} \FloatTok{0.3}\NormalTok{) }\SpecialCharTok{+} \CommentTok{\# 箱ひげ図}
   \FunctionTok{geom\_violin}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.3}\NormalTok{) }\SpecialCharTok{+}               \CommentTok{\# バイオリンプロット}
    \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{size =} \DecValTok{5}\NormalTok{)) }\SpecialCharTok{+}
   \FunctionTok{facet\_wrap}\NormalTok{(}\FunctionTok{vars}\NormalTok{(variables), }\AttributeTok{scales =} \StringTok{"free"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{gisho12_files/figure-latex/unnamed-chunk-62-1.pdf}

詳しくは特別付録の\href{https://izunyan.github.io/practice_ggplot2/}{ggplot2の辞書}を参照ください。

\hypertarget{ux76f8ux95a2ux306eux78baux8a8d}{%
\section{相関の確認}\label{ux76f8ux95a2ux306eux78baux8a8d}}

変数同士の相関関係を見たいという要望はビジネス、アカデミックを問わず多く発生すると思います。簡単な相関行列の出し方やその可視化について解説します。ここで便利なパッケージが\texttt{corrr}です。

\hypertarget{ux76f8ux95a2ux884cux5217ux3092ux51faux3059}{%
\subsection{相関行列を出す}\label{ux76f8ux95a2ux884cux5217ux3092ux51faux3059}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(corrr)}
\end{Highlighting}
\end{Shaded}

まずペンギンデータの中の数値変数だけにしぼります。そして、yearはここでは不要なので落とします。そうして作ったデータフレーム\texttt{cor\_df}を、\texttt{correlate()}関数に入れるだけです。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cor\_df }\OtherTok{\textless{}{-}} 
\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{select}\NormalTok{(}\FunctionTok{where}\NormalTok{(is.numeric)) }\SpecialCharTok{\%\textgreater{}\%} \CommentTok{\# 数値変数だけにしぼる}
  \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{year)                 }\CommentTok{\# 不要なので落とす  }


\FunctionTok{correlate}\NormalTok{(cor\_df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 4 x 5
##   term  bill_length_mm bill_depth_mm flipper_length_~ body_mass_g
##   <chr>          <dbl>         <dbl>            <dbl>       <dbl>
## 1 bill~         NA            -0.235            0.656       0.595
## 2 bill~         -0.235        NA               -0.584      -0.472
## 3 flip~          0.656        -0.584           NA           0.871
## 4 body~          0.595        -0.472            0.871      NA
\end{verbatim}

上側と下型で相関係数が重複しているので、片側だけを残したい場合があります。その際は\texttt{shave()}関数で簡単に重複部分をなくせます。引数に\texttt{upper\ =\ FALSE}と入れれば、上側だけにすることもできます。

相関係数の表示したい桁の指定は、\texttt{fashion()}関数で、引数に\texttt{decimals\ =}で桁数を指定することで可能になります。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cormat }\OtherTok{\textless{}{-}} 
\FunctionTok{correlate}\NormalTok{(cor\_df) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{shave}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{fashion}\NormalTok{(}\AttributeTok{decimals =} \DecValTok{1}\NormalTok{)}

\NormalTok{cormat}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                term bill_length_mm bill_depth_mm flipper_length_mm body_mass_g
## 1    bill_length_mm                                                           
## 2     bill_depth_mm            -.2                                            
## 3 flipper_length_mm             .7           -.6                              
## 4       body_mass_g             .6           -.5                .9
\end{verbatim}

あとは、以下のように出力するだけです。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{write\_xlsx}\NormalTok{(cormat, }\StringTok{"out/相関行列.xlsx"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{ux76f8ux95a2ux884cux5217ux306eux53efux8996ux5316}{%
\subsection{相関行列の可視化}\label{ux76f8ux95a2ux884cux5217ux306eux53efux8996ux5316}}

\texttt{corrr}パッケージの関数で相関行列の可視化も簡単にできます。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{correlate}\NormalTok{(cor\_df) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{rplot}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{gisho12_files/figure-latex/unnamed-chunk-67-1.pdf}

\hypertarget{ux3042ux3068ux304cux304d}{%
\chapter*{あとがき}\label{ux3042ux3068ux304cux304d}}
\addcontentsline{toc}{chapter}{あとがき}

初めての同人誌執筆が終わろうとしています。執筆に用いたBookdownについて前より理解が深まったと同時に、全然わからないことも増えました。。執筆途中で、メインで使っていたノートPCの充電ができなくなるというアクシデントにも見舞われました。こうした様々な学びを活かして、次回作につなげられればと思います。

本書の執筆にあたり、同人誌制作の先輩である\texttt{天川榎@EnokiAmakawa}氏から背中押し＆多くの助言をいただきました。この場を借りてお礼申し上げます。

この本の内容が、なるべく多くの方に届いて、みんなの仕事の効率化につながればうれしいです。そして、Rの可能性がさらに多くの方に認識され、Rを使ってお仕事できる環境が一層整っていくことを願ってやみません。

\clearpage
\vspace*{\stretch{1}}
\begin{flushright}
\begin{minipage}{0.5\hsize}
\begin{description}
  \item{著者：} やわらかクジラ
  \item{発行：} 2020年9月12日
  \item{サークル名：} ヤサイゼリー
  \item{twitter：} @matsuchiy
  \item{印刷：} 電子出版のみ
\end{description}
\end{minipage}
\end{flushright}
\clearpage

\end{document}
